# -*- coding: utf-8 -*-
"""Copy of for_loop_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAbEQtTbX9W8dmJMEFbT5utYF59kbjPh

## Question 1 (Easy)

**Title:** Print 1 to 10

### Problem Statement:
Print numbers from 1 to 10 using a for loop.

### Approach:
Use `range(1, 11)` inside a `for` loop and print each value.
"""

# write your code here
range(1,11)
for i in range(1,11):
  print(i)

"""## Question 2 (Easy)

**Title:** Sum of First N Numbers

### Problem Statement:
Take an integer N as input and find the sum of numbers from 1 to N.

### Approach:
Initialize sum = 0, loop from 1 to N, add each value to sum.

"""

# write your code here
n=int(input())
sum=0
for i in range(1,n+1):
  sum=sum+i

print(sum)

"""## Question 3 (Easy)

**Title:** Even Numbers from 1 to 50

### Problem Statement:
Print all even numbers between 1 and 50.

### Approach:
Loop from 1 to 50 and check `i % 2 == 0`.

"""

# write your code here

for i in range(1,50):
  if i%2==0:
    print(i)

# for i in range(2,51,2):
#   print(i)

"""## Question 4 (Easy)

**Title:** Count Multiples of 3

### Problem Statement:
Take N as input and count how many numbers between 1 and N are divisible by 3.

### Approach:
Use a counter variable and increment when `i % 3 == 0`.

"""

# write your code here
n=int(input())
count=0
for i in range(1,n+1):
  if i%3==0:
    count=count+1

print(count)

"""## Question 5 (Easy)

**Title:** Multiplication Table

### Problem Statement:
Take a number as input and print its multiplication table from 1 to 10.

### Approach:
Loop from 1 to 10 and multiply with the input number.

"""

# write your code here
num=int(input("enter a number"))

for i in range(1,11):
  print(num,"x","=",num * i)

"""## Question 6 (Easy)

**Title:** Factorial of a Number

### Problem Statement:
Take a number N as input and find its factorial.

### Approach:
Initialize fact = 1 and multiply values from 1 to N.

"""

# write your code here
n=int(input())

fact=1

for i in range(1,n+1):
  fact=fact*i

print(fact)

"""## Question 7 (Easy)

**Title:** Running Sum

### Problem Statement:
Take N as input and print the running sum from 1 to N.

### Approach:
Use a sum variable and update it in each iteration.

"""

# write your code here

n=int(input())

sum=0
for i in range(1, n+1):
  sum=sum+i

print(sum)

"""## Question 8 (Easy)

**Title:** Add 5 to Each Number

### Problem Statement:
Take N as input and add 5 to each number from 1 to N and print the result.

### Approach:
Loop from 1 to N and use shorthand `value += 5`.

"""

# write your code here
n=int(input())

for i in range(1,n+1):
  print(i+5)

"""## Question 9 (Easy)

**Title:** Count Even and Odd Numbers

### Problem Statement:
Take N as input and count how many even and odd numbers are there between 1 and N.

### Approach:
Use two counters and check with modulo operator.

"""

# write your code here
n=int(input())

even_count=0
odd_count=0

for i in range(1,n+1):
  if i%2==0:
    even_count+=1

  else:
    odd_count+=1

print(even_count)
print(odd_count)

"""## Question 10 (Easy)

**Title:** Squares from 1 to N

### Problem Statement:
Take N as input and print the square of each number from 1 to N.

### Approach:
Use `i * i` inside the loop.

"""

# write your code here
n=int(input())

for i in range(1,n+1):
  print(i*i)

"""## Question 11 (Medium)

**Title:** Sum of Even and Odd Separately

### Problem Statement:
Take N as input and find the sum of all even numbers and all odd numbers between 1 and N.

### Approach:
Use two sum variables and check each number with modulo.

"""

# write your code here
n=int(input())

even_sum=0
odd_sum=0


for i in range(1,n+1):
  if i%2==0:
    even_sum=even_sum+i

  else:
    odd_sum=odd_sum+i

print(even_sum)
print(odd_sum)

"""## Question 12 (Medium)

**Title:** Divisible by 3 and 5

### Problem Statement:
Take N as input and count how many numbers between 1 and N are divisible by both 3 and 5.

### Approach:
Use logical AND condition inside the loop.

"""

# write your code here
n=int(input())
count=0
for i in range(1,n+1):
  if i%3==0 and i%5==0:
    count+=1

print("count:",count)

"""## Question 13 (Medium)

**Title:** Skip Multiples of 4

### Problem Statement:
Take N as input and print numbers from 1 to N but skip multiples of 4.

### Approach:
Use `continue` when the number is divisible by 4.

"""

# write your code here
n=int(input())

for i in range(1,n+1):
  if i%4==0:
    continue
  print(i)

"""## Question 14 (Medium)

**Title:** Find the Largest Number

### Problem Statement:
Take N as input and find the largest number between 1 and N using a loop.

### Approach:
Assume the first value as largest and update using `if`.

"""

# write your code here
n=int(input())
largest=0
for i in range(1,n+1):
  if i>largest:
    largest=i

print(largest)

"""## Question 15 (Medium)

**Title:** Power of a Number

### Problem Statement:
Take two numbers `a` and `b` as input and calculate `a` raised to the power `b` using a for loop.

### Approach:
Initialize result = 1 and multiply it `b` times.

"""

# write your code here
a=int(input("enter base number(a): "))
b=int(input("enter power number(b): "))

result=1
for i in range(1,b+1):
  result=result*a

print(result)

"""## Question 16 (Hard)

**Title:** Check Prime Number

### Problem Statement:
Take a number as input and check whether it is prime or not.

### Approach:
Loop from 2 to N-1 and use `break` if divisible.

"""

# write your code here
n=int(input())
for i in range(2,n):
  if n%i==0:
    print("not prime")
    break
  else:
    print("prime")

"""## Question 17 (Hard)

**Title:** Prime Numbers Between 1 and N

### Problem Statement:
Take N as input and print all prime numbers between 1 and N.

### Approach:
Use nested loops and a flag variable for prime checking.

"""

# write your code here
n=int(input())

for i in range(2,n+1):
  for j in range(2,i):
    if i%j==0:
      break
  else:
    print(i)

"""## Question 18 (Hard)

**Title:** First Number Divisible by 7 and 11

### Problem Statement:
Take N as input and find the first number between 1 and N that is divisible by both 7 and 11. Stop after finding it.

### Approach:
Use logical AND and stop the loop using `break`.

"""

# write your code here
n=int(input())
for i in range(1,n+1):
  if i%7==0 and i%11==0:
    print("first number divisible by 7 and 11 is:", i)
    break

else:
  print("no found between 1 and ",n)

"""## Question 19 (Hard)

**Title:** Number Pattern

### Problem Statement:
Take N as input and print a right-angled number pattern using nested loops.

Example:
1
12
123

### Approach:
Use an outer loop for rows and an inner loop for printing numbers.

"""

# write your code here

var=int(input())

for i in range(1,var+1):
  for j in range(1,i+1):
    print(j, end="")
  print()

count=0
for i in range(2):
  n=10
  while n>4:
    count=count+1
    print("Class over", count)
    n=n-1

# run for loop inside while loop
n=12
while n>10:
  for i in range(3):
    print("jai hind and i is : ",i )
  n=n-1